export const imageCounts = {
  Cloud: 6,
  Tifa: 5,
  Aeris: 5,
  Barret: 3,
  Sephiroth: 3,
  Cid: 2,
  Bugenhagen: 3,
  Yuffie: 2,
  Vincent: 1,
  'Red XIII': 2,
  'Cait Sith': 3,
  default: 10,
}

export const verbs = {
  Cloud: 'Converse',
  Tifa: 'Talk',
  Aeris: 'Articulate',
  Barret: 'Banter',
  Sephiroth: 'Speak',
  Bugenhagen: 'Babble',
  Yuffie: 'Yap',
  Cid: 'Chat',
  'Red XIII': 'Roar',
  'Cait Sith': 'Confess',
  Hojo: 'Hypothesize',
  Rufus: 'Rant',
  Reno: 'Ramble',
  Scarlet: 'Sneer',
  Heidegger: 'Holler',
  Tseng: 'Tell',
  Vincent: 'Voice',
  Elena: 'Exclaim',
  Dyne: 'Declare',
  Rude: 'Remark',
  Elmyra: 'Explain',
  Shera: 'Share',
  Corneo: 'Croon',
  Reeve: 'Relay',
  Jessie: 'Jabber',
  Palmer: 'Prattle',
  Dio: 'Discourse',
  Godo: 'Grumble',
  'Don Corneo': 'Drawl',
  Mukki: 'Murmur',
  Priscilla: 'Proclaim',
  Ester: 'Utter',
  'Mr.Coates': 'Mutter',
  'Flower girl': 'Flutter',
  Doctor: 'Deliberate',
  Biggs: 'Blurt',
  Clerk: 'Chatter',
  Marlene: 'Marvel',
  Lucrecia: 'Lament',
  Wedge: 'Whisper',
  Joe: 'Jest',
  Holzoff: 'Holler',
  Scotch: 'Spout',
  Johnny: 'Jaw',
  'Shinra soldier': 'Shout',
  'Party leader': 'Pitch',
  'Chocobo Sage': 'Chirp',
  Chole: 'Chime in',
  Staniv: 'State',
  Chekhov: 'Chime',
  Princess: 'Pronounce',
  Cashier: 'Call out',
  'Choco Bill': 'Chatter',
  Song: 'Sing',
  'TV Producer': 'Transmit',
  Sign: 'Signal',
  'Shinra manager': 'Summon',
  'Mr. Hangman': 'Mouth off',
  'Elder Hargo': 'Expound',
  Party: 'Parley',
  Commander: 'Command',
  Gast: 'Gasp',
  default: 'Talk',
}
